name: Build Windows EXE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile
        run: |
          cl /EHsc /DWIN32 /D_WINDOWS main.cpp user32.lib ws2_32.lib

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: dhcp-detector
          path: main.exe
